name: build-2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 8 */6 * *' # every 6 days
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  git-only:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      # 1. Checkout the master branch properly
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          repository: ac1dburnz/docker-vsyuuno
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master  # ensures we are on master, not detached HEAD
          fetch-depth: 0 # fetch full history, needed for push

      # 2. Configure Git user for commits
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Add, commit, and push changes (if any)
      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Automated commit from workflow"
          git push origin master


